export interface IregisterCompanyEmployee {
     roles_id: number[],
     email: string,
     password: string,
     additional_roles?: string | null,
     address: string,
     bank_account?: string | null,
     city?: string | null,
     cnic: string | null,
     cnic_date_of_birth?: string | null,
     current_base_salary?: number | '',
     date_of_birth?: string | null,
     date_of_joining?: string | null, 
     department?: string | null, 
     designation?: string | null, 
     employee_id: string, 
     hobbies?: string | null,
     increment_amount?: number | '', 
     initial_base_salary?: number | '', 
     last_increment_date?: string | null, 
     name: string, 
     phone?: string,
     state?: string, 
     vehicle_registration_number?: string, 
     zip?: string
}